version: "3"

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  sqs:
    image: softwaremill/elasticmq-native:1.5.4
    ports:
      - "9324:9324"
      - "9325:9325"
